spring:
  application:
    name: pagme
  datasource:
    url: jdbc:postgresql://localhost:5432/pagme_local
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  jpa:
    open-in-view: false
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
        default_schema: PGM




